// Automatically generated by Andrey Murugov's code-generator. Do not edit!!!


const op_t op_instr_set[] =
{
	{HASH_MUL, 	 funcMUL},
	{HASH_ADD,   funcADD},
	{HASH_SUB, 	 funcSUB},
	{HASH_DIV, 	 funcDIV},
	{HASH_POW, 	 funcPOW},
	{HASH_COS, 	 funcCOS},
	{HASH_SIN, 	 funcSIN},
	{HASH_TAN, 	 funcTAN}
};

#define LEN_INSTR_SET sizeof(op_instr_set) / sizeof(*op_instr_set)