// Automatically generated by Andrey Murugov's code-generator. Do not edit!!!


const op_t op_instr_set[] =
{
	{HASH_MUL,     "*",       calcMUL,     diffMUL},
	{HASH_ADD,     "+",       calcADD,     diffADD},
	{HASH_SUB,     "-",       calcSUB,     diffSUB},
	{HASH_DIV,     "/",       calcDIV,     diffDIV},
	{HASH_POW,     "^",       calcPOW,     diffPOW},
	{HASH_E,       "e",       calcE,       diffE},
	{HASH_LN,      "ln",      calcLN,      diffLN},
	{HASH_COS,     "cos",     calcCOS,     diffCOS},
	{HASH_COT,     "cot",     calcCOT,     diffCOT},
	{HASH_LOG,     "log",     calcLOG,     diffLOG},
	{HASH_SIN,     "sin",     calcSIN,     diffSIN},
	{HASH_TAN,     "tan",     calcTAN,     diffTAN},
	{HASH_COSH,    "tanh",    calcCOSH,    diffCOSH},
	{HASH_COTH,    "coth",    calcCOTH,    diffCOTH},
	{HASH_SINH,    "sinh",    calcSINH,    diffSINH},
	{HASH_TANH,    "tanh",    calcTANH,    diffTANH},
	{HASH_ARCCOS,  "arccos",  calcARCCOS,  diffARCCOS},
	{HASH_ARCCOT,  "arccot",  calcARCCOT,  diffARCCOT},
	{HASH_ARCSIN,  "arcsin",  calcARCSIN,  diffARCSIN},
	{HASH_ARCTAN,  "arctan",  calcARCTAN,  diffARCTAN},
	{HASH_ARCCOSH, "arccosh", calcARCCOSH, diffARCCOSH},
	{HASH_ARCCOTH, "arccoth", calcARCCOTH, diffARCCOTH},
	{HASH_ARCSINH, "arcsinh", calcARCSINH, diffARCSINH},
	{HASH_ARCTANH, "arctanh", calcARCTANH, diffARCTANH}
};

#define LEN_INSTR_SET sizeof(op_instr_set) / sizeof(*op_instr_set)