// Automatically generated by Andrey Murugov's code-generator. Do not edit!!!


#ifndef WOLF_OP_H
#define WOLF_OP_H

enum HashOp
{
    HASH_MUL = 42,
    HASH_ADD = 43,
    HASH_SUB = 45,
    HASH_DIV = 47,
    HASH_POW = 94,
    HASH_COS = 98695,
    HASH_SIN = 113880,
    HASH_TAN = 114593
};

struct op_context
{
    node_t  *node_1;
    node_t  *node_2;
};

WolfErr_t funcADD(op_context *op_params);
WolfErr_t funcSUB(op_context *op_params);
WolfErr_t funcMUL(op_context *op_params);
WolfErr_t funcDIV(op_context *op_params);
WolfErr_t funcPOW(op_context *op_params);
WolfErr_t funcSIN(op_context *op_params);
WolfErr_t funcCOS(op_context *op_params);
WolfErr_t funcTAN(op_context *op_params);

typedef WolfErr_t (*func_t)(op_context *op_params);

struct op_t
{
    HashOp  hash;
    func_t  func;
};

#endif