// Automatically generated by Andrey Murugov's code-generator. Do not edit!!!


#ifndef WOLF_OP_H
#define WOLF_OP_H

enum WolfErr_t
{
    WOLF_SUCCESS = 0,
    WOLF_ERROR   = 1
};

enum HashOp
{
    HASH_MUL     = 0x2A,     
    HASH_ADD     = 0x2B,     
    HASH_SUB     = 0x2D,     
    HASH_DIV     = 0x2F,     
    HASH_POW     = 0x5E,     
    HAHS_E       = 0x65, 
    HASH_LG      = 0xD7B, 
    HASH_COS     = 0x181E7,
    HASH_COT     = 0x181E8,
    HASH_LOG     = 0x1A344,  
    HASH_SIN     = 0x1BC78,  
    HASH_TAN     = 0x1BFA1,  
    HASH_COSH    = 0x2EAC1,  
    HASH_COTH    = 0x2EAE0,  
    HASH_SINH    = 0x35D50,  
    HASH_TANH    = 0x36367,  
    HASH_ARCCOS  = 0xABFBF75,
    HASH_ARCCOT  = 0xABFBF76,
    HASH_ARCSIN  = 0xABFC246,
    HAHS_ARCTAN  = 0xABFC48F,
    HASH_ARCCOSH = 0x14D29FE53,
    HASH_ARCCOTH = 0x14D29FE62,
    HASH_ARCSINH = 0x14D2C1D62,
    HAHS_ARCTANH = 0x14D2C1EB9 
};

struct calc_context
{
    double left_val;
    double right_val;
};


struct diff_context
{
    node_t *node_left;
    node_t *node_right;
    hash_t hash_indep_var;
};


// elementary functions

double calcADD(calc_context *calc_params);
node_t *diffADD(diff_context *diff_params);

double calcSUB(calc_context *calc_params);
node_t *diffSUB(diff_context *diff_params);

double calcMUL(calc_context *calc_params);
node_t *diffMUL(diff_context *diff_params);

double calcDIV(calc_context *calc_params);
node_t *diffDIV(diff_context *diff_params);

double calcPOW(calc_context *calc_params);
node_t *diffPOW(diff_context *diff_params);


// exponential functions

double calcEXP(calc_context *calc_params);
node_t *diffEXP(diff_context *diff_params);

double calcLG(calc_context *calc_params);
node_t *diffLG(diff_context *diff_params);

double calcLOG(calc_context *calc_params);
node_t *diffLOG(diff_context *diff_params);


// trigonometric functions

double calcSIN(calc_context *calc_params);
node_t *diffSIN(diff_context *diff_params);

double calcCOS(calc_context *calc_params);
node_t *diffCOS(diff_context *diff_params);

double calcTAN(calc_context *calc_params);
node_t *diffTAN(diff_context *diff_params);

double calcCOT(calc_context *calc_params);
node_t *diffCOT(diff_context *diff_params);


// hyperbolic functions

double calcSINH(calc_context *calc_params);
node_t *diffSINH(diff_context *diff_params);

double calcCOSH(calc_context *calc_params);
node_t *diffCOSH(diff_context *diff_params);

double calcTANH(calc_context *calc_params);
node_t *diffTANH(diff_context *diff_params);

double calcCOTH(calc_context *calc_params);
node_t *diffCOTH(diff_context *diff_params);


// inverse trigonometric functions

double calcARCSIN(calc_context *calc_params);
node_t *diffARCSIN(diff_context *diff_params);

double calcARCCOS(calc_context *calc_params);
node_t *diffARCCOS(diff_context *diff_params);

double calcARCTAN(calc_context *calc_params);
node_t *diffARCTAN(diff_context *diff_params);

double calcARCCOT(calc_context *calc_params);
node_t *diffARCCOT(diff_context *diff_params);


// inverse hyperbolic functions

double calcARCSINH(calc_context *calc_params);
node_t *diffARCSINH(diff_context *diff_params);

double calcARCCOSH(calc_context *calc_params);
node_t *diffARCCOSH(diff_context *diff_params);

double calcARCTANH(calc_context *calc_params);
node_t *diffARCTANH(diff_context *diff_params);

double calcARCCOTH(calc_context *calc_params);
node_t *diffARCCOTH(diff_context *diff_params);


typedef double (*calc_t)(calc_context *calc_params);
typedef node_t *(*diff_t)(diff_context *diff_params);

struct op_t
{
    HashOp  hash;
    char name[8];
    calc_t  calc;
    diff_t  diff;
};

#endif