#include "WolfGen.h"


int main()
{
    // FILE *SourceFile     = fopen("./GENERATOR/src/func.txt", "r");
    // if (IS_BAD_PTR(SourceFile)) { perror(ANSI_COLOR_RED "Bad pointer SourceFile:" ANSI_COLOR_RESET); return 1; }
    
    // FILE *WolfOpFile     = fopen("./GENERATOR/ReportFiles/WolfOp.h", "w");
    // if (IS_BAD_PTR(WolfOpFile)) { perror(ANSI_COLOR_RED "Bad pointer WolfOpFile:" ANSI_COLOR_RESET); return 1; }
    
    // FILE *OpInstrSetFile = fopen("./GENERATOR/ReportFiles/OpInstrSet.cpp", "w");
    // if (IS_BAD_PTR(OpInstrSetFile)) { perror(ANSI_COLOR_RED "Bad pointer OpInstrSetFile:" ANSI_COLOR_RESET); return 1; }


    // char* buffer = NULL;
    // size_t len_buffer = 0;
    // size_t count_line = 0;
    // char **arr_ptr = TXTreader(SourceFile, buffer, &len_buffer, &count_line, NULL);
    // if (IS_BAD_PTR(arr_ptr))
    //     perror(ANSI_COLOR_RED "Error reading SourceFile!" ANSI_COLOR_RESET);


    // RemoveComments(arr_ptr, &count_line);

    // if (GenWolfOp(WolfOpFile, arr_ptr, count_line))
    //     perror(ANSI_COLOR_RED "Error creating WolfOpFile!" ANSI_COLOR_RESET);
    // else
    //     printf(ANSI_COLOR_GREEN "SUCCESS\n" ANSI_COLOR_RESET);

    // if (GenOpInstrSet(OpInstrSetFile, arr_ptr, count_line))
    //     perror(ANSI_COLOR_RED "Error creating OpInstrSetFile!" ANSI_COLOR_RESET);
    // else
    //     printf(ANSI_COLOR_GREEN "SUCCESS\n" ANSI_COLOR_RESET);

    // free(arr_ptr);
    // fclose(SourceFile);
    // fclose(WolfOpFile);
    // fclose(OpInstrSetFile);
    
    char op[8] = {0};
    scanf("%s", op);
    printf("%s: %zu\n", op, HashStr(op));
    return 0;
}


void RemoveComments(char** arr_cmd, size_t *count_line)
{
    for (size_t i = 0; i < *count_line; ++i)
    {
        char* colon = strchr(arr_cmd[i], '#');

        if (colon != NULL)
            *colon = '\0';
    }
}


GenErr_t GenWolfOp(FILE *WolfOpFile, char **arr_ptr, size_t count_line)
{
    if (IS_BAD_PTR(WolfOpFile) || IS_BAD_PTR(arr_ptr) || count_line < 0) return GEN_ERROR;
        
    fprintf(WolfOpFile, "// Automatically generated by Andrey Murugov's code-generator. Do not edit!!!\n\n\n");

    unsigned int max_num_cmd = 0;
    unsigned int min_num_cmd = 32;

    char cmd[8] = {0};
    char op[8]  = {0};

    fprintf(WolfOpFile, "#ifndef WOLF_OP_H\n"
                        "#define WOLF_OP_H\n\n");

    fprintf(WolfOpFile, "enum HashOp\n");
    fprintf(WolfOpFile, "{\n");
    for (size_t line = 0; line < count_line - 1; ++line)
    {
        if (sscanf(arr_ptr[line], "%s: \"%s\";", cmd, op) == 2)
            fprintf(WolfOpFile, "\tHASH_%s = 0x%02X,\n", cmd, HashStr(op));

        else
            return GEN_ERROR;
    }
    if (sscanf(arr_ptr[count_line - 1], "%s: \"%s\";", cmd, op) == 2)
        fprintf(WolfOpFile, "\tHASH_%s = 0x%02X,\n", cmd, HashStr(op));

    else
        return GEN_ERROR;
    fprintf(WolfOpFile, "};\n\n");

    
    
    free(cmd);

    return GEN_SUCCESS;
}


// int CmpByHash(const void *a, const void *b)
// {
//     const asm_instr_t *arr_instr_a = (const asm_instr_t*)a;
//     const asm_instr_t *arr_instr_b = (const asm_instr_t*)b;

//     if (arr_instr_a->hash > arr_instr_b->hash)
//         return 1;
//     if (arr_instr_a->hash == arr_instr_b->hash)
//         return 0;
//     return -1;
// }