// Automatically generated by Andrey Murugov's code-generator. Do not edit!!!


enum CmdCodes
{
	CMD_HLT      = 0x00,
	CMD_PUSH     = 0x01,
	CMD_POP      = 0x02,
	CMD_ADD      = 0x03,
	CMD_SUB      = 0x04,
	CMD_MUL      = 0x05,
	CMD_DIV      = 0x06,
	CMD_SQRT     = 0x07,
	CMD_IN       = 0x08,
	CMD_OUT      = 0x09,
	CMD_JMP      = 0x0A,
	CMD_JE       = 0x0B,
	CMD_JNE      = 0x0C,
	CMD_JA       = 0x0D,
	CMD_JAE      = 0x0E,
	CMD_JB       = 0x0F,
	CMD_JBE      = 0x10,
	CMD_CALL     = 0x11,
	CMD_RET      = 0x12,
	CMD_MOV      = 0x13
};

#define MAX_NUM_CMD 19
#define MIN_NUM_CMD 0
