// Automatically generated by Andrey Murugov's code-generator. Do not edit!!!

const keyword_t keyword_set[] =
{
	{TOKEN_LPAREN   , "(",	1 ,	0x28},
	{TOKEN_RPAREN   , ")",	1 ,	0x29},
	{TOKEN_MUL      , "*",	1 ,	0x2A},
	{TOKEN_ADD      , "+",	1 ,	0x2B},
	{TOKEN_COMMA    , ",",	1 ,	0x2C},
	{TOKEN_SUB      , "-",	1 ,	0x2D},
	{TOKEN_DIV      , "/",	1 ,	0x2F},
	{TOKEN_COLON    , ":",	1 ,	0x3A},
	{TOKEN_SEMICOLON, ";",	1 ,	0x3B},
	{TOKEN_EQ       , "=",	1 ,	0x3D},
	{TOKEN_LBRACKET , "[",	1 ,	0x5B},
	{TOKEN_RBRACKET , "]",	1 ,	0x5D},
	{TOKEN_POW      , "^",	1 ,	0x5E},
	{TOKEN_LBRACE   , "{",	1 ,	0x7B},
	{TOKEN_RBRACE   , "}",	1 ,	0x7D},
	{TOKEN_EQEQ     , "==",	2 ,	0x7A0},
	{TOKEN_IF       , "if",	2 ,	0xD1D},
	{TOKEN_DEF      , "def",	3 ,	0x18405},
	{TOKEN_FOR      , "for",	3 ,	0x18CC9},
	{TOKEN_ELSE     , "else",	4 ,	0x2F8D39},
	{TOKEN_WHILE    , "while",	5 ,	0x6BDCB31},
	{TOKEN_RETURN   , "return",	6 ,	0xC84E3D30}
};

#define LEN_KEYWORD_SET sizeof(keyword_set) / sizeof(*keyword_set)
