// Automatically generated by Andrey Murugov's code generator. Do not edit!!!


const WrapCmd spu_instr_set[] =
{
	{FUNC_CMD_HLT,      0,	 CMD_HLT},
	{FUNC_CMD_PUSH,     1,	 CMD_PUSH},
	{FUNC_CMD_POP,      1,	 CMD_POP},
	{FUNC_CMD_ADD,      0,	 CMD_ADD},
	{FUNC_CMD_SUB,      0,	 CMD_SUB},
	{FUNC_CMD_MUL,      0,	 CMD_MUL},
	{FUNC_CMD_DIV,      0,	 CMD_DIV},
	{FUNC_CMD_SQRT,     0,	 CMD_SQRT},
	{FUNC_CMD_IN,       0,	 CMD_IN},
	{FUNC_CMD_OUT,      0,	 CMD_OUT},
	{FUNC_CMD_JMP,      1,	 CMD_JMP},
	{FUNC_CMD_JE,       1,	 CMD_JE},
	{FUNC_CMD_JNE,      1,	 CMD_JNE},
	{FUNC_CMD_JA,       1,	 CMD_JA},
	{FUNC_CMD_JAE,      1,	 CMD_JAE},
	{FUNC_CMD_JB,       1,	 CMD_JB},
	{FUNC_CMD_JBE,      1,	 CMD_JBE},
	{FUNC_CMD_CALL,     1,	 CMD_CALL},
	{FUNC_CMD_RET,      0,	 CMD_RET},
	{FUNC_CMD_MOV,      2,	 CMD_MOV}
};

#define LEN_INSTR_SET sizeof(spu_instr_set) / sizeof(*spu_instr_set)