// Automatically generated by Andrey Murugov's code-generator. Do not edit!!!

#ifndef WOLF_OP_H
#define WOLF_OP_H


enum HashOp
{
	HASH_L_PAREN    = 0x0,
	HASH_R_PAREN    = 0x29,
	HASH_L_BRACKET  = 0x5B,
	HASH_R_BRACKET  = 0x5D,
	HASH_L_BRACE    = 0x7B,
	HASH_R_BRACE    = 0x7D,
	HASH_EQUAL      = 0x3D,
	HASH_COMMA      = 0x2C,
	HASH_SEMICOLON  = 0x3B,
	HASH_DEF        = 0x18405,
	HASH_DERIVATIVE = 0x44,
	HASH_PLOT       = 0x348CE1,
	HASH_ADD        = 0x2B,
	HASH_SUB        = 0x2D,
	HASH_MUL        = 0x2A,
	HASH_DIV        = 0x2F,
	HASH_POW        = 0x5E,
	HASH_SQRT       = 0x35FD20,
	HASH_E          = 0x65,
	HASH_LN         = 0xD82,
	HASH_LOG        = 0x1A344,
	HASH_SIN        = 0x1BCD8,
	HASH_COS        = 0x18187,
	HASH_TAN        = 0x1BFA1,
	HASH_COT        = 0x18188,
	HASH_SINH       = 0x35DE90,
	HASH_COSH       = 0x2EAFC1,
	HASH_TANH       = 0x3634E7,
	HASH_COTH       = 0x2EAFE0,
	HASH_ARCSIN     = 0xABFB4946,
	HASH_ARCCOS     = 0xABFB0DF5,
	HASH_ARCTAN     = 0xABFB4C0F,
	HASH_ARCCOT     = 0xABFB0DF6,
	HASH_ARCSINH    = 0x14D36DDFE2,
	HASH_ARCCOSH    = 0x14D366B113,
	HASH_ARCTANH    = 0x14D36E3639,
	HASH_ARCCOTH    = 0x14D366B132
};

struct calc_context
{
    double left_val;
    double right_val;
};

struct diff_context
{
    node_t *node_left;
    node_t *node_right;
    hash_t hash_indep_var;
};


double calcADD(calc_context *calc_params);
node_t *diffADD(diff_context *diff_params);

double calcSUB(calc_context *calc_params);
node_t *diffSUB(diff_context *diff_params);

double calcMUL(calc_context *calc_params);
node_t *diffMUL(diff_context *diff_params);

double calcDIV(calc_context *calc_params);
node_t *diffDIV(diff_context *diff_params);

double calcPOW(calc_context *calc_params);
node_t *diffPOW(diff_context *diff_params);

double calcSQRT(calc_context *calc_params);
node_t *diffSQRT(diff_context *diff_params);

double calcE(calc_context *calc_params);
node_t *diffE(diff_context *diff_params);

double calcLN(calc_context *calc_params);
node_t *diffLN(diff_context *diff_params);

double calcLOG(calc_context *calc_params);
node_t *diffLOG(diff_context *diff_params);

double calcSIN(calc_context *calc_params);
node_t *diffSIN(diff_context *diff_params);

double calcCOS(calc_context *calc_params);
node_t *diffCOS(diff_context *diff_params);

double calcTAN(calc_context *calc_params);
node_t *diffTAN(diff_context *diff_params);

double calcCOT(calc_context *calc_params);
node_t *diffCOT(diff_context *diff_params);

double calcSINH(calc_context *calc_params);
node_t *diffSINH(diff_context *diff_params);

double calcCOSH(calc_context *calc_params);
node_t *diffCOSH(diff_context *diff_params);

double calcTANH(calc_context *calc_params);
node_t *diffTANH(diff_context *diff_params);

double calcCOTH(calc_context *calc_params);
node_t *diffCOTH(diff_context *diff_params);

double calcARCSIN(calc_context *calc_params);
node_t *diffARCSIN(diff_context *diff_params);

double calcARCCOS(calc_context *calc_params);
node_t *diffARCCOS(diff_context *diff_params);

double calcARCTAN(calc_context *calc_params);
node_t *diffARCTAN(diff_context *diff_params);

double calcARCCOT(calc_context *calc_params);
node_t *diffARCCOT(diff_context *diff_params);

double calcARCSINH(calc_context *calc_params);
node_t *diffARCSINH(diff_context *diff_params);

double calcARCCOSH(calc_context *calc_params);
node_t *diffARCCOSH(diff_context *diff_params);

double calcARCTANH(calc_context *calc_params);
node_t *diffARCTANH(diff_context *diff_params);

double calcARCCOTH(calc_context *calc_params);
node_t *diffARCCOTH(diff_context *diff_params);

typedef double (*calc_t)(calc_context *calc_params);
typedef node_t *(*diff_t)(diff_context *diff_params);


#endif
